server:
  port: 8081

#database credentials
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/citizen?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

#database connection
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#euraka name
  application:
    name: CITIZEN-SERVICE
